# This file defines the services for the local demo environment.

services:
  # Vault Server: The in-theater security control plane.
  vault-server:
    image: "hashicorp/vault:1.20"
    container_name: "vault-server-demo"
    ports:
      - "8200:8200"
    environment:
      # Run in dev mode for simplicity. Auto-unseals.
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK

  # Demo Controller: The Node.js API and Web GUI server.
  demo-controller:
    build:
      context: ./demo-controller
    ports:
      - "8080:8080"
    # SECURITY NOTE: Mounting the Docker socket is a security risk and is done here
    # only to allow the demo controller to trigger administrative actions on the
    # Vault container for the interactive scenarios.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vault-server

  # Stryker Agent: A placeholder representing a vehicle agent.
  stryker-agent-1:
    image: "alpine:latest"
    # Keep the container running indefinitely.
    command: tail -f /dev/null
