# .github/workflows/ci.yml
# This workflow tests the local demo setup process.

name: Continuous Integration

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Make the run script executable
      - name: Make script executable
        run: chmod +x run-demo.sh

      # 3. Run the setup script
      # This script now handles building, starting, and configuring the containers.
      - name: Run setup script
        run: ./run-demo.sh

      # 4. Health Check - Web GUI
      # This confirms the demo-controller started and is serving the webpage.
      - name: Health Check - Web GUI
        run: curl --fail http://localhost:8080

      # 5. Health Check - Vault Server
      # This confirms the Vault server is running and unsealed.
      - name: Health Check - Vault Server
        run: curl --fail http://localhost:8200/v1/sys/health
